// Spanish unit descriptions. part of ../unit_descriptions.dart.
// Una oración por unidad; factores de lib/logic/unit_data.dart.

part of '../unit_descriptions.dart';

const Map<UnitCategory, Map<String, String>> _unitDescEs = {
  UnitCategory.count: {
    'items': 'Unidades — la unidad base para contar, una pieza.',
    'dz': 'Docena — doce unidades.',
    'gr': 'Gruesa — una docena de docenas, es decir, 144 unidades.',
    'ggr': 'Gran gruesa — una docena de gruesas, es decir, 1728 unidades.',
    'ones': 'Unos — una pieza, la unidad base en el sistema decimal.',
    'ten': 'Decena — diez unidades.',
    'hundred': 'Centena — diez decenas, es decir, 100 unidades.',
    'thousand': 'Millar — diez centenas, es decir, 1000 unidades.',
  },
  UnitCategory.dist: {
    'in': 'Pulgada — longitud imperial; doce pulgadas forman un pie (2,54 cm).',
    'ft': 'Pie — longitud imperial de doce pulgadas (30,48 cm).',
    'yd': 'Yarda — tres pies (0,9144 m).',
    'mi': 'Milla — 1760 yardas, la medida de camino imperial habitual (1,609 km).',
    'fathom': 'Braza — medida náutica de profundidad del agua, seis pies (1,8288 m).',
    'nmi': 'Milla náutica — un minuto de arco en la circunferencia terrestre, exactamente 1852 m.',
    'league': 'Legua — históricamente una hora de caminata, tres millas (4,828 km).',
    'mm': 'Milímetro — una milésima de metro.',
    'cm': 'Centímetro — una centésima de metro.',
    'm': 'Metro — unidad base del SI de longitud.',
    'km': 'Kilómetro — mil metros.',
  },
  UnitCategory.area: {
    'sq in': 'Pulgada cuadrada — el área de un cuadrado de una pulgada de lado.',
    'sq ft': 'Pie cuadrado — área de un cuadrado de un pie de lado; 144 pulgadas cuadradas.',
    'sq yd': 'Yarda cuadrada — área de un cuadrado de una yarda de lado; nueve pies cuadrados.',
    'acre': 'Acre — antigua medida agraria, 4840 yardas cuadradas (unos 4047 m²).',
    'sq mi': 'Milla cuadrada — área de un cuadrado de una milla de lado; 640 acres.',
    'cm²': 'Centímetro cuadrado — área de un cuadrado de un centímetro de lado.',
    'm²': 'Metro cuadrado — unidad SI de área; un cuadrado de un metro de lado.',
    'ha': 'Hectárea — 10000 metros cuadrados, un cuadrado de 100 m de lado.',
    'km²': 'Kilómetro cuadrado — área de un cuadrado de un kilómetro de lado.',
  },
  UnitCategory.space: {
    'cu in': 'Pulgada cúbica — el volumen de un cubo de una pulgada de arista.',
    'cu ft': 'Pie cúbico — volumen de un cubo de un pie de arista; 1728 pulgadas cúbicas.',
    'cu yd': 'Yarda cúbica — volumen de un cubo de una yarda de arista; 27 pies cúbicos.',
    'cm³': 'Centímetro cúbico — volumen de un cubo de 1 cm de arista (un mililitro).',
    'm³': 'Metro cúbico — unidad SI de volumen; un cubo de un metro de arista.',
  },
  UnitCategory.weight: {
    'oz': 'Onza — peso imperial, una dieciseisava parte de una libra (28,35 g).',
    'lb': 'Libra — peso imperial de 16 onzas (453,6 g).',
    'st': 'Stone — medida británica de peso corporal, 14 libras (6,35 kg).',
    'cwt': 'Hundredweight — quintal corto estadounidense de 100 libras (45,36 kg).',
    'ton': 'Tonelada corta — tonelada estadounidense de 2000 libras (907,2 kg).',
    'oz t': 'Onza troy — peso para metales preciosos, algo más pesada que la onza común (31,1 g).',
    'g': 'Gramo — una milésima de kilogramo.',
    'kg': 'Kilogramo — unidad base del SI de masa.',
    't': 'Tonelada — mil kilogramos.',
  },
  UnitCategory.time: {
    's': 'Segundo — unidad base del SI de tiempo.',
    'min': 'Minuto — sesenta segundos.',
    'h': 'Hora — sesenta minutos.',
    'd': 'Día — veinticuatro horas.',
    'week': 'Semana — siete días.',
  },
  UnitCategory.angle: {
    '°': 'Grado — la trescientos sesentava parte de una vuelta completa.',
    '′': 'Minuto de arco — una sexagésima parte de un grado.',
    '″': 'Segundo de arco — una sexagésima parte de un minuto de arco.',
    'sign': 'Signo — un signo del zodíaco, 30°, una doceava parte del círculo completo.',
    'turn': 'Vuelta — el círculo completo, 360° o 2π.',
    'gon': 'Gon (gradián) — una cuatrocentésima parte de la vuelta completa; el ángulo recto mide 100 gon.',
    'rad': 'Radián — unidad SI de ángulo; el ángulo cuyo arco es igual al radio.',
  },
  UnitCategory.price: {
    'd': 'Penique (antiguo, «d» de denarius) — en la antigua moneda británica, una doceava parte de un chelín.',
    'sh': 'Chelín — en la antigua moneda británica, una veinteava parte de una libra, doce peniques.',
    '£': 'Libra esterlina — la unidad monetaria principal del Reino Unido.',
    'guinea': 'Guinea — moneda histórica equivalente a una libra y un chelín (21 chelines).',
    'p': 'Penique (nuevo) — una centésima de libra desde la decimalización de 1971.',
    '£dec': 'Libra (decimal) — la libra actual de 100 (nuevos) peniques.',
  },
  UnitCategory.temp: {
    '°F': 'Grado Fahrenheit — escala donde el agua se congela a 32° y hierve a 212°.',
    '°R': 'Grado Rankine — escala absoluta con el mismo intervalo que °F; el 0 es el cero absoluto.',
    '°C': 'Grado Celsius — escala donde el agua se congela a 0° y hierve a 100°.',
    'K': 'Kelvin — unidad base del SI de temperatura, contada desde el cero absoluto.',
  },
  UnitCategory.press: {
    'psi': 'Libras por pulgada cuadrada — presión imperial (un lbf sobre una superficie de una pulgada cuadrada).',
    'inHg': 'Pulgadas de mercurio — la presión que sostiene una columna de mercurio de una pulgada de altura.',
    'Pa': 'Pascal — unidad SI de presión; un newton por metro cuadrado.',
    'kPa': 'Kilopascal — mil pascales.',
    'bar': 'Bar — 100000 pascales, cercano a la presión atmosférica media al nivel del mar.',
    'atm': 'Atmósfera estándar — presión atmosférica media al nivel del mar (101325 pascales).',
    'mmHg': 'Milímetros de mercurio (torr) — presión de una columna de mercurio de un milímetro de altura.',
  },
  UnitCategory.force: {
    'lbf': 'Libra-fuerza — la fuerza gravitatoria de una libra (4,448 N).',
    'pdl': 'Poundal — unidad imperial de fuerza que acelera una libra a 1 ft/s² (0,138 N).',
    'N': 'Newton — unidad SI de fuerza; acelera un kilogramo a 1 m/s².',
    'kN': 'Kilonewton — mil newtons.',
    'kgf': 'Kilopondio — la fuerza gravitatoria de un kilogramo (9,807 N).',
    'dyn': 'Dina — unidad CGS de fuerza; acelera un gramo a 1 cm/s² (10⁻⁵ N).',
  },
  UnitCategory.work: {
    'BTU': 'Unidad Térmica Británica — calor que eleva un grado °F la temperatura de una libra de agua (1055 J).',
    'ft·lbf': 'Pie-libra — trabajo de mover una libra-fuerza a lo largo de un pie (1,356 J).',
    'J': 'Julio — unidad SI de energía; un newton a lo largo de un metro.',
    'kJ': 'Kilojulio — mil julios.',
    'Wh': 'Vatio-hora — energía de un vatio de potencia durante una hora (3600 J).',
    'kWh': 'Kilovatio-hora — mil vatios-hora, la unidad habitual de las facturas eléctricas.',
    'cal': 'Caloría — calor que eleva 1 °C la temperatura de un gramo de agua (4,184 J).',
    'kcal': 'Kilocaloría — mil calorías; la «caloría» de la nutrición.',
  },
  UnitCategory.power: {
    'hp': 'Caballo de vapor (mecánico, imperial) — unos 745,7 vatios.',
    'BTU/h': 'BTU por hora — medida de potencia usada principalmente en climatización y calefacción (0,293 W).',
    'W': 'Vatio — unidad SI de potencia; un julio por segundo.',
    'kW': 'Kilovatio — mil vatios.',
    'PS': 'Caballo de vapor (métrico) — 735,5 vatios.',
  },
  UnitCategory.cook: {
    'tsp': 'Cucharadita (US) — medida de cocina, un tercio de cucharada (4,93 ml).',
    'tbsp': 'Cucharada (US) — medida de cocina de tres cucharaditas (14,79 ml).',
    'fl oz': 'Onza líquida (US) — medida de volumen para líquidos (29,57 ml).',
    'cup': 'Taza (US) — medida de cocina de ocho onzas líquidas (236,6 ml).',
    'pint': 'Pinta (US) — dos tazas, es decir, 16 onzas líquidas (473,2 ml).',
    'mL': 'Mililitro — una milésima de litro, es decir, un centímetro cúbico.',
    'L': 'Litro — medida métrica de volumen, un decímetro cúbico.',
  },
  UnitCategory.liquid: {
    'fl oz': 'Onza líquida (US) — medida de volumen para líquidos (29,57 ml).',
    'gill': 'Gill — antigua medida de líquidos, un cuarto de pinta (118,3 ml).',
    'pint': 'Pinta (US) — 16 onzas líquidas, es decir, cuatro gills (473,2 ml).',
    'quart': 'Cuarto — un cuarto de galón, es decir, dos pintas (0,946 l).',
    'gallon': 'Galón (US) — cuatro cuartos (3,785 l).',
    'mL': 'Mililitro — una milésima de litro.',
    'L': 'Litro — medida métrica de volumen, un decímetro cúbico.',
  },
  UnitCategory.moment: {
    'lbf·ft': 'Pie-libra — par de torsión de una libra-fuerza en una palanca de un pie (1,356 N·m).',
    'lbf·in': 'Pulgada-libra — par de torsión de una libra-fuerza en una palanca de una pulgada (0,113 N·m).',
    'N·m': 'Newton-metro — unidad SI de par de torsión; un newton en una palanca de un metro.',
    'kN·m': 'Kilonewton-metro — mil newton-metros.',
    'kgf·m': 'Kilopondio-metro — par de torsión de un kilopondio en una palanca de un metro (9,807 N·m).',
  },
};
