// Irish unit descriptions. part of ../unit_descriptions.dart.
part of '../unit_descriptions.dart';

const Map<UnitCategory, Map<String, String>> _unitDescGa = {
  UnitCategory.count: {
    'items': 'Míreanna aonair — an bunaonad comhairimh, mír amháin.',
    'dz': 'Dosaen — dhá mhír dhéag.',
    'gr': 'Gros — dosaen dosaeanna, is é sin 144 mír.',
    'ggr': 'Mór-ghros — dosaen gros, is é sin 1728 mír.',
    'ones': 'Aonaid — mír amháin, an bunaonad sa chóras deachúil.',
    'ten': 'Deichniúr — deich mír.',
    'hundred': 'Céad — deich ndeich, is é sin 100 mír.',
    'thousand': 'Míle — deich gcéad, is é sin 1000 mír.',
  },
  UnitCategory.dist: {
    'in': 'Orlach — tomhas faid impiriúil; dhá orlach dhéag sa troigh (2,54 cm).',
    'ft': 'Troigh — tomhas faid impiriúil de dhá orlach dhéag (30,48 cm).',
    'yd': 'Slat — trí troigh (0,9144 m).',
    'mi': 'Míle — 1760 slat, an tomhas bóthair impiriúil coitianta (1,609 km).',
    'fathom': 'Feadán — tomhas mara ar dhoimhneacht uisce, sé troigh (1,8288 m).',
    'nmi': 'Míle farraige — nóiméad aon bhogha ar imlíne an Domhain, 1852 m go beacht.',
    'league': 'Léig — stairiúil timpeall uair an chloig siúil, trí mhíle (4,828 km).',
    'mm': 'Millméadar — míléadú den mhéadar.',
    'cm': 'Ceintiméadar — céadú den mhéadar.',
    'm': 'Méadar — bunaonad SI den fhad.',
    'km': 'Ciliméadar — míle méadar.',
  },
  UnitCategory.area: {
    'sq in': 'Orlach cearnach — achar cearnóige a bhfuil orlach amháin ar a taobh.',
    'sq ft': 'Troigh chearnach — achar cearnóige a bhfuil troigh amháin ar a taobh; 144 orlach cearnach.',
    'sq yd': 'Slat chearnach — achar cearnóige a bhfuil slat amháin ar a taobh; naoi dtroigh cearnach.',
    'acre': 'Acra — seantomhas páirce, 4840 slat chearnach (thart ar 4047 m²).',
    'sq mi': 'Míle cearnach — achar cearnóige a bhfuil míle amháin ar a taobh; 640 acra.',
    'cm²': 'Ceintiméadar cearnach — achar cearnóige a bhfuil ceintiméadar amháin ar a taobh.',
    'm²': 'Méadar cearnach — aonad SI an achair; cearnóg a bhfuil méadar amháin ar a taobh.',
    'ha': 'Heicteár — 10000 méadar cearnach, cearnóg a bhfuil 100 m ar a taobh.',
    'km²': 'Ciliméadar cearnach — achar cearnóige a bhfuil ciliméadar amháin ar a taobh.',
  },
  UnitCategory.space: {
    'cu in': 'Orlach ciúbach — toirt ciúibe a bhfuil orlach amháin ar a hél.',
    'cu ft': 'Troigh chiúbach — toirt ciúibe a bhfuil troigh amháin ar a hél; 1728 orlach ciúbach.',
    'cu yd': 'Slat chiúbach — toirt ciúibe a bhfuil slat amháin ar a hél; 27 troigh chiúbach.',
    'cm³': 'Ceintiméadar ciúbach — toirt ciúibe a bhfuil 1 cm ar a hél (millilítear amháin).',
    'm³': 'Méadar ciúbach — aonad SI na toirte; ciúb a bhfuil méadar amháin ar a hél.',
  },
  UnitCategory.weight: {
    'oz': 'Unsa — tomhas meáchain impiriúil, séú cuid déag den phunt (28,35 g).',
    'lb': 'Punt — tomhas meáchain impiriúil de 16 unsa (453,6 g).',
    'st': 'Cloch — tomhas Briotanach meáchain coirp, 14 punt (6,35 kg).',
    'cwt': 'Céadphunt — céadphunt gearr Meiriceánach de 100 punt (45,36 kg).',
    'ton': 'Tona ghearr — tona Meiriceánach de 2000 punt (907,2 kg).',
    'oz t': 'Unsa Troy — meáchan d’mhiotail lómhara, rud beag níos troime ná an gnáth-unsa (31,1 g).',
    'g': 'Gram — míléadú den chileagram.',
    'kg': 'Cileagram — bunaonad SI na mais.',
    't': 'Tona — míle cileagram.',
  },
  UnitCategory.time: {
    's': 'Soicind — bunaonad SI an ama.',
    'min': 'Nóiméad — seasca soicind.',
    'h': 'Uair an chloig — seasca nóiméad.',
    'd': 'Lá — ceithre huaire is fiche.',
    'week': 'Seachtain — seacht lá.',
  },
  UnitCategory.angle: {
    '°': 'Céim — trí chéad is seascadú cuid den chasadh iomlán.',
    '′': 'Nóiméad bogha — seascadú cuid de chéim.',
    '″': 'Soicind bogha — seascadú cuid de nóiméad bogha.',
    'sign': 'Comhartha — comhartha zoidiaigh amháin, 30°, cuid den chiorcal iomlán ina dhá chuid dhéag.',
    'turn': 'Casadh iomlán — an ciorcal iomlán, 360° nó 2π.',
    'gon': 'Gon (graidean) — ceathrú céadú den chasadh iomlán; is é 100 gon an ceann dronuillinn.',
    'rad': 'Radián — tomhas uillinne SI; an uillinn a bhfuil a stuán chomh fada leis an gha.',
  },
  UnitCategory.price: {
    'd': 'Pingin (ársa, “d” ón denarius) — an dóú cuid déag den scilling in airgead ársa na Breataine.',
    'sh': 'Scilling — an fichiú cuid den phunt in airgead ársa na Breataine, dhá phingin dhéag.',
    '£': 'Punt sterling — príomhaonad airgeadra na Breataine.',
    'guinea': 'Ginea — bonn stairiúil ar fiú punt agus scilling amháin é (21 scilling).',
    'p': 'Pingin (nua) — céadú den phunt ó dhéicheálú 1971.',
    '£dec': 'Punt (deachúil) — an punt comhaimseartha de 100 pingin (nua).',
  },
  UnitCategory.temp: {
    '°F': 'Céim Fahrenheit — scála le pointe reo uisce ag 32° agus pointe fiuchta ag 212°.',
    '°R': 'Céim Rankine — scála absalóideach le céimeanna méide Fahrenheit; is é 0 an nialas absalóideach.',
    '°C': 'Céim Celsius — scála le pointe reo uisce ag 0° agus pointe fiuchta ag 100°.',
    'K': 'Ceilvin — bunaonad SI na teochta, arna chomhaireamh ón nialas absalóideach.',
  },
  UnitCategory.press: {
    'psi': 'Punt in aghaidh an orlaigh chearnach — brú impiriúil (lbf amháin ar achar orlach cearnach).',
    'inHg': 'Orlach colún mearcair — an brú a choinníonn colún mearcair orlach amháin ar airde.',
    'Pa': 'Pascal — aonad SI an bhrú; newton amháin in aghaidh an mhéadair chearnach.',
    'kPa': 'Cileapascal — míle pascal.',
    'bar': 'Bar — 100000 pascal, gar do mheánbhrú aeir ar leibhéal na farraige.',
    'atm': 'Atmaisféar caighdeánach — meánbhrú aeir ar leibhéal na farraige (101325 pascal).',
    'mmHg': 'Millméadar colún mearcair (torr) — brú colún mearcair millméadar amháin ar airde.',
  },
  UnitCategory.force: {
    'lbf': 'Fórsa puint — fórsa meáchain punt amháin (4,448 N).',
    'pdl': 'Poundal — fórsa impiriúil a luasghéaraíonn punt amháin ag 1 ft/s² (0,138 N).',
    'N': 'Newton — aonad SI an fhórsa; luasghéaraíonn cileagram amháin ag 1 m/s².',
    'kN': 'Cileanewton — míle newton.',
    'kgf': 'Fórsa cileagram — fórsa meáchain cileagram amháin (9,807 N).',
    'dyn': 'Dín — aonad fórsa CGS; luasghéaraíonn gram amháin ag 1 cm/s² (10⁻⁵ N).',
  },
  UnitCategory.work: {
    'BTU': 'British Thermal Unit — teas a théann punt amháin uisce de 1 °F (1055 J).',
    'ft·lbf': 'Troigh-punt — obair chun fórsa punt amháin a bhogadh ar feadh troigh (1,356 J).',
    'J': 'Joule — aonad SI na fuinnimh; newton amháin ar feadh méadar amháin.',
    'kJ': 'Cileajoule — míle joule.',
    'Wh': 'Vata-uair — fuinneamh vata amháin chumhachta ar feadh uair an chloig (3600 J).',
    'kWh': 'Cileavatuair — míle vata-uair, an gnáthaonad ar bhillí leictreachais.',
    'cal': 'Calra — teas a théann gram amháin uisce de 1 °C (4,184 J).',
    'kcal': 'Cilecalra — míle calra; an “calra” cothaithe.',
  },
  UnitCategory.power: {
    'hp': 'Cumhacht capaill (meicniúil, impiriúil) — thart ar 745,7 vata.',
    'BTU/h': 'BTU in aghaidh na huaire — tomhas cumhachta a úsáidtear go príomha sa téamh agus san fhuarú (0,293 W).',
    'W': 'Vata — aonad SI na cumhachta; joule amháin in aghaidh na soicinde.',
    'kW': 'Cileavata — míle vata.',
    'PS': 'Cumhacht capaill (méadrach) — 735,5 vata.',
  },
  UnitCategory.cook: {
    'tsp': 'Taespúnóg (US) — tomhas cócaireachta, trian spúnóige bhoird (4,93 ml).',
    'tbsp': 'Spúnóg bhoird (US) — tomhas cócaireachta de thrí thaespúnóg (14,79 ml).',
    'fl oz': 'Unsa leachtach (US) — tomhas toirte do leachtanna (29,57 ml).',
    'cup': 'Cupán (US) — tomhas cócaireachta d’ocht n-unsa leachta (236,6 ml).',
    'pint': 'Pionta (US) — dhá chupán, is é sin 16 unsa leachta (473,2 ml).',
    'mL': 'Millilítear — míléadú den lítear, is é sin ceintiméadar ciúbach amháin.',
    'L': 'Lítear — tomhas toirte méadrach, deiméadar ciúbach amháin.',
  },
  UnitCategory.liquid: {
    'fl oz': 'Unsa leachtach (US) — tomhas toirte do leachtanna (29,57 ml).',
    'gill': 'Gill — seantomhas leachta, ceathrú pionta (118,3 ml).',
    'pint': 'Pionta (US) — 16 unsa leachta nó ceithre gill (473,2 ml).',
    'quart': 'Cárt — ceathrú galún nó dhá phionta (0,946 l).',
    'gallon': 'Galún (US) — ceithre cárt (3,785 l).',
    'mL': 'Millilítear — míléadú den lítear.',
    'L': 'Lítear — tomhas toirte méadrach, deiméadar ciúbach amháin.',
  },
  UnitCategory.moment: {
    'lbf·ft': 'Punt-troigh — móimint fhórsa puint ar luamhán troigh amháin ar fhad (1,356 N·m).',
    'lbf·in': 'Punt-orlach — móimint fhórsa puint ar luamhán orlach amháin ar fhad (0,113 N·m).',
    'N·m': 'Newton-méadar — aonad SI na móiminte; newton amháin ar luamhán méadar amháin ar fhad.',
    'kN·m': 'Cileanewton-méadar — míle newton-méadar.',
    'kgf·m': 'Fórsa-cileagram-méadar — móimint fhórsa cileagram ar luamhán méadar amháin ar fhad (9,807 N·m).',
  },
};
