// Welsh unit descriptions. part of ../unit_descriptions.dart.
part of '../unit_descriptions.dart';

const Map<UnitCategory, Map<String, String>> _unitDescCy = {
  UnitCategory.count: {
    'items': 'Eitemau unigol — yr uned sylfaenol ar gyfer cyfrif, un darn.',
    'dz': 'Dwsin — deuddeg eitem.',
    'gr': 'Gros — dwsin o ddwsinau, sef 144 eitem.',
    'ggr': 'Gros mawr — dwsin o rosau, sef 1728 eitem.',
    'ones': 'Unedau — un eitem, yr uned sylfaenol yn y system ddegol.',
    'ten': 'Deg — deg eitem.',
    'hundred': 'Cant — deg degau, sef 100 eitem.',
    'thousand': 'Mil — deg cant, sef 1000 eitem.',
  },
  UnitCategory.dist: {
    'in': 'Modfedd — mesur hyd imperialaidd; deuddeg modfedd sy’n gwneud troedfedd (2.54 cm).',
    'ft': 'Troedfedd — mesur hyd imperialaidd o ddeuddeg modfedd (30.48 cm).',
    'yd': 'Llath — tair troedfedd (0.9144 m).',
    'mi': 'Milltir — 1760 llath, y mesur ffordd imperialaidd cyffredin (1.609 km).',
    'fathom': 'Gwryd — mesur morwrol dyfnder dŵr, chwe throedfedd (1.8288 m).',
    'nmi': 'Milltir forwrol — un munud arc ar amgylchedd y Ddaear, union 1852 m.',
    'league': 'Lîg — hanesyddol tua awr o gerdded, tair milltir (4.828 km).',
    'mm': 'Milimetr — un milfed ran o fetr.',
    'cm': 'Centimetr — un ganfed ran o fetr.',
    'm': 'Metr — uned sylfaenol SI ar gyfer hyd.',
    'km': 'Cilometr — mil o fetrau.',
  },
  UnitCategory.area: {
    'sq in': 'Modfedd sgwâr — arwynebedd sgwâr ag un fodfedd o ochr.',
    'sq ft': 'Troedfedd sgwâr — arwynebedd sgwâr ag un droedfedd o ochr; 144 modfedd sgwâr.',
    'sq yd': 'Llath sgwâr — arwynebedd sgwâr ag un llath o ochr; naw troedfedd sgwâr.',
    'acre': 'Erw — hen fesur cae, 4840 llath sgwâr (tua 4047 m²).',
    'sq mi': 'Milltir sgwâr — arwynebedd sgwâr ag un filltir o ochr; 640 erw.',
    'cm²': 'Centimetr sgwâr — arwynebedd sgwâr ag un centimetr o ochr.',
    'm²': 'Metr sgwâr — uned SI ar gyfer arwynebedd; sgwâr ag un metr o ochr.',
    'ha': 'Hectar — 10000 metr sgwâr, sgwâr 100 m o ochr.',
    'km²': 'Cilometr sgwâr — arwynebedd sgwâr ag un cilometr o ochr.',
  },
  UnitCategory.space: {
    'cu in': 'Modfedd giwbig — cyfaint ciwb ag un fodfedd o ymyl.',
    'cu ft': 'Troedfedd giwbig — cyfaint ciwb ag un droedfedd o ymyl; 1728 modfedd giwbig.',
    'cu yd': 'Llath giwbig — cyfaint ciwb ag un llath o ymyl; 27 troedfedd giwbig.',
    'cm³': 'Centimetr ciwbig — cyfaint ciwb 1 cm o ymyl (un mililitr).',
    'm³': 'Metr ciwbig — uned SI ar gyfer cyfaint; ciwb ag un metr o ymyl.',
  },
  UnitCategory.weight: {
    'oz': 'Owns — pwysau imperialaidd, un rhan o un ar bymtheg o bwys (28.35 g).',
    'lb': 'Pwys — pwysau imperialaidd o 16 owns (453.6 g).',
    'st': 'Stôn — mesur pwysau corff Prydeinig, 14 pwys (6.35 kg).',
    'cwt': 'Canpwys (hundredweight) — canpwys byr yr UD o 100 pwys (45.36 kg).',
    'ton': 'Tunnell fyr — tunnell yr UD o 2000 pwys (907.2 kg).',
    'oz t': 'Owns Troy — pwysau ar gyfer metelau gwerthfawr, ychydig yn drymach na’r owns arferol (31.1 g).',
    'g': 'Gram — un milfed ran o gilogram.',
    'kg': 'Cilogram — uned sylfaenol SI ar gyfer màs.',
    't': 'Tunnell fetrig — mil o gilogramau.',
  },
  UnitCategory.time: {
    's': 'Eiliad — uned sylfaenol SI ar gyfer amser.',
    'min': 'Munud — trigain eiliad.',
    'h': 'Awr — trigain munud.',
    'd': 'Diwrnod — pedair awr ar hugain.',
    'week': 'Wythnos — saith diwrnod.',
  },
  UnitCategory.angle: {
    '°': 'Gradd — un rhan o dri chant a thrigain o dro llawn.',
    '′': 'Munud arc — un rhan o drigain o radd.',
    '″': 'Eiliad arc — un rhan o drigain o funud arc.',
    'sign': 'Arwydd — un arwydd sidyddol, 30°, un rhan o ddeuddeg o’r cylch llawn.',
    'turn': 'Tro — y cylch llawn, 360° neu 2π.',
    'gon': 'Gon (gradian) — un rhan o bedwar cant o dro llawn; mae ongl sgwâr yn 100 gon.',
    'rad': 'Radian — mesur ongl SI; yr ongl y mae ei harc yn hafal i’r radiws.',
  },
  UnitCategory.price: {
    'd': 'Ceiniog (hen, "d" am denarius) — un rhan o ddeuddeg o swllt yn hen arian Prydain.',
    'sh': 'Swllt — un rhan o ugain o bunt yn hen arian Prydain, deuddeg ceiniog.',
    '£': 'Punt sterling — prif uned arian cyfred Prydain.',
    'guinea': 'Gini — darn arian hanesyddol gwerth punt a swllt (21 swllt).',
    'p': 'Ceiniog (newydd) — un ganfed ran o bunt ers degoliad 1971.',
    '£dec': 'Punt (degol) — y bunt bresennol o 100 ceiniog (newydd).',
  },
  UnitCategory.temp: {
    '°F': 'Gradd Fahrenheit — graddfa gyda rhewbwynt dŵr ar 32° a berwbwynt ar 212°.',
    '°R': 'Gradd Rankine — graddfa absoliwt â chamau maint Fahrenheit; 0 yw sero absoliwt.',
    '°C': 'Gradd Celsius — graddfa gyda rhewbwynt dŵr ar 0° a berwbwynt ar 100°.',
    'K': 'Kelvin — uned sylfaenol SI ar gyfer tymheredd, yn cychwyn o sero absoliwt.',
  },
  UnitCategory.press: {
    'psi': 'Pwys y fodfedd sgwâr — gwasgedd imperialaidd (un lbf ar arwynebedd modfedd sgwâr).',
    'inHg': 'Modfeddi o fercwri — y gwasgedd sy’n dal colofn fercwri un fodfedd o uchder.',
    'Pa': 'Pascal — uned SI gwasgedd; un newton y metr sgwâr.',
    'kPa': 'Cilopascal — mil o bascalau.',
    'bar': 'Bar — 100000 pascal, yn agos at wasgedd aer cyfartalog ar lefel y môr.',
    'atm': 'Atmosffer safonol — gwasgedd aer cyfartalog ar lefel y môr (101325 pascal).',
    'mmHg': 'Milimetrau o fercwri (torr) — gwasgedd colofn fercwri un milimetr o uchder.',
  },
  UnitCategory.force: {
    'lbf': 'Grym pwys — grym pwysedd un pwys (4.448 N).',
    'pdl': 'Poundal — grym imperialaidd sy’n cyflymu un pwys ar 1 ft/s² (0.138 N).',
    'N': 'Newton — uned SI grym; cyflyma un cilogram ar 1 m/s².',
    'kN': 'Cilonewton — mil o newtonau.',
    'kgf': 'Grym cilogram — grym pwysedd un cilogram (9.807 N).',
    'dyn': 'Dein — uned grym CGS; cyflyma un gram ar 1 cm/s² (10⁻⁵ N).',
  },
  UnitCategory.work: {
    'BTU': 'Uned Thermol Brydeinig (BTU) — gwres sy’n cynhesu un pwys o ddŵr 1 °F (1055 J).',
    'ft·lbf': 'Troedfedd-pwys — gwaith symud un pound-force drwy un droedfedd (1.356 J).',
    'J': 'Joule — uned SI egni; un newton dros un metr.',
    'kJ': 'Cilojoule — mil o jouleau.',
    'Wh': 'Wat-awr — egni un wat o bŵer dros un awr (3600 J).',
    'kWh': 'Cilowat-awr — mil o wat-oriau, yr uned arferol ar filiau trydan.',
    'cal': 'Calori — gwres sy’n cynhesu un gram o ddŵr 1 °C (4.184 J).',
    'kcal': 'Cilocalori — mil o galorïau; y “calori” maeth.',
  },
  UnitCategory.power: {
    'hp': 'Marchnerth (mecanyddol, imperialaidd) — tua 745.7 wat.',
    'BTU/h': 'BTU yr awr — mesur pŵer a ddefnyddir yn bennaf mewn gwres a oeri (0.293 W).',
    'W': 'Wat — uned SI pŵer; un joule yr eiliad.',
    'kW': 'Cilowat — mil o watiau.',
    'PS': 'Marchnerth metrig — 735.5 wat.',
  },
  UnitCategory.cook: {
    'tsp': 'Llwyaid de (UD) — mesur coginio, un rhan o dair llwy fwrdd (4.93 ml).',
    'tbsp': 'Llwy fwrdd (UD) — mesur coginio o dair llwyaid de (14.79 ml).',
    'fl oz': 'Owns hylif (UD) — mesur cyfaint ar gyfer hylifau (29.57 ml).',
    'cup': 'Cwpanaid (UD) — mesur coginio o wyth owns hylif (236.6 ml).',
    'pint': 'Peint (UD) — dau gwpanaid, sef 16 owns hylif (473.2 ml).',
    'mL': 'Mililitr — un milfed ran o litr, sef un centimetr ciwbig.',
    'L': 'Litr — mesur cyfaint metrig, un desimetr ciwbig.',
  },
  UnitCategory.liquid: {
    'fl oz': 'Owns hylif (UD) — mesur cyfaint ar gyfer hylifau (29.57 ml).',
    'gill': 'Gill — hen fesur hylif, chwarter peint (118.3 ml).',
    'pint': 'Peint (UD) — 16 owns hylif, sef pedwar gill (473.2 ml).',
    'quart': 'Chwart — chwarter galwyn, sef dau beint (0.946 l).',
    'gallon': 'Galwyn (UD) — pedwar chwart (3.785 l).',
    'mL': 'Mililitr — un milfed ran o litr.',
    'L': 'Litr — mesur cyfaint metrig, un desimetr ciwbig.',
  },
  UnitCategory.moment: {
    'lbf·ft': 'Pwys-troedfedd — trorym un pound-force ar lifar un droedfedd o hyd (1.356 N·m).',
    'lbf·in': 'Pwys-fodfedd — trorym un pound-force ar lifar un fodfedd o hyd (0.113 N·m).',
    'N·m': 'Newton-metr — uned SI trorym; un newton ar lifar un metr o hyd.',
    'kN·m': 'Cilonewton-metr — mil o newton-metrau.',
    'kgf·m': 'Grym cilogram-metr — trorym un grym cilogram ar lifar un metr o hyd (9.807 N·m).',
  },
};
