// French unit descriptions. part of ../unit_descriptions.dart.
part of '../unit_descriptions.dart';

const Map<UnitCategory, Map<String, String>> _unitDescFr = {
  UnitCategory.count: {
    'items': 'Pièces — l’unité de base du comptage, une pièce individuelle.',
    'dz': 'Douzaine — douze pièces.',
    'gr': 'Grosse — une douzaine de douzaines, soit 144 pièces.',
    'ggr': 'Grande grosse — une douzaine de grosses, soit 1728 pièces.',
    'ones': 'Unités — une pièce, l’unité de base dans le système décimal.',
    'ten': 'Dizaine — dix pièces.',
    'hundred': 'Centaine — dix dizaines, soit 100 pièces.',
    'thousand': 'Millier — dix centaines, soit 1000 pièces.',
  },
  UnitCategory.dist: {
    'in': 'Pouce — mesure de longueur impériale ; douze pouces font un pied (2,54 cm).',
    'ft': 'Pied — mesure de longueur impériale de douze pouces (30,48 cm).',
    'yd': 'Yard — trois pieds (0,9144 m).',
    'mi': 'Mille — 1760 yards, la mesure de distance impériale courante (1,609 km).',
    'fathom': 'Brasse — mesure nautique de profondeur d’eau, six pieds (1,8288 m).',
    'nmi': 'Mille marin — une minute d’arc sur la circonférence terrestre, exactement 1852 m.',
    'league': 'Lieue — historiquement environ une heure de marche, trois milles (4,828 km).',
    'mm': 'Millimètre — un millième de mètre.',
    'cm': 'Centimètre — un centième de mètre.',
    'm': 'Mètre — unité de base SI de longueur.',
    'km': 'Kilomètre — mille mètres.',
  },
  UnitCategory.area: {
    'sq in': 'Pouce carré — surface d’un carré d’un pouce de côté.',
    'sq ft': 'Pied carré — surface d’un carré d’un pied de côté ; 144 pouces carrés.',
    'sq yd': 'Yard carré — surface d’un carré d’un yard de côté ; neuf pieds carrés.',
    'acre': 'Acre — ancienne mesure agraire, 4840 yards carrés (environ 4047 m²).',
    'sq mi': 'Mille carré — surface d’un carré d’un mille de côté ; 640 acres.',
    'cm²': 'Centimètre carré — surface d’un carré d’un centimètre de côté.',
    'm²': 'Mètre carré — unité SI de surface ; un carré d’un mètre de côté.',
    'ha': 'Hectare — 10000 mètres carrés, un carré de 100 m de côté.',
    'km²': 'Kilomètre carré — surface d’un carré d’un kilomètre de côté.',
  },
  UnitCategory.space: {
    'cu in': 'Pouce cube — volume d’un cube d’un pouce d’arête.',
    'cu ft': 'Pied cube — volume d’un cube d’un pied d’arête ; 1728 pouces cubes.',
    'cu yd': 'Yard cube — volume d’un cube d’un yard d’arête ; 27 pieds cubes.',
    'cm³': 'Centimètre cube — volume d’un cube de 1 cm d’arête (un millilitre).',
    'm³': 'Mètre cube — unité SI de volume ; un cube d’un mètre d’arête.',
  },
  UnitCategory.weight: {
    'oz': 'Once — poids impérial, un seizième de livre (28,35 g).',
    'lb': 'Livre — poids impérial de 16 onces (453,6 g).',
    'st': 'Stone — mesure britannique de poids corporel, 14 livres (6,35 kg).',
    'cwt': 'Hundredweight — quintal américain de 100 livres (45,36 kg).',
    'ton': 'Tonne courte — tonne américaine de 2000 livres (907,2 kg).',
    'oz t': 'Once troy — poids pour les métaux précieux, légèrement plus lourde que l’once ordinaire (31,1 g).',
    'g': 'Gramme — un millième de kilogramme.',
    'kg': 'Kilogramme — unité de base SI de masse.',
    't': 'Tonne — mille kilogrammes.',
  },
  UnitCategory.time: {
    's': 'Seconde — unité de base SI du temps.',
    'min': 'Minute — soixante secondes.',
    'h': 'Heure — soixante minutes.',
    'd': 'Jour — vingt-quatre heures.',
    'week': 'Semaine — sept jours.',
  },
  UnitCategory.angle: {
    '°': 'Degré — un trois-cent-soixantième d’un tour complet.',
    '′': 'Minute d’arc — un soixantième de degré.',
    '″': 'Seconde d’arc — un soixantième de minute d’arc.',
    'sign': 'Signe — un signe du zodiaque, 30°, un douzième du cercle entier.',
    'turn': 'Tour — le cercle complet, 360° soit 2π.',
    'gon': 'Grade — un quatre-centième du tour complet ; l’angle droit mesure 100 grades.',
    'rad': 'Radian — mesure d’angle SI ; l’angle dont l’arc est égal au rayon.',
  },
  UnitCategory.price: {
    'd': 'Penny (ancien, « d » pour denarius) — un douzième de shilling dans l’ancien système monétaire britannique.',
    'sh': 'Shilling — un vingtième de livre dans l’ancien système monétaire britannique, douze pence.',
    '£': 'Livre sterling — l’unité monétaire principale britannique.',
    'guinea': 'Guinée — pièce historique valant une livre et un shilling (21 shillings).',
    'p': 'Penny (nouveau) — un centième de livre depuis la décimalisation de 1971.',
    '£dec': 'Livre (décimale) — la livre actuelle de 100 (nouveaux) pence.',
  },
  UnitCategory.temp: {
    '°F': 'Degré Fahrenheit — échelle où l’eau gèle à 32° et bout à 212°.',
    '°R': 'Degré Rankine — échelle absolue avec des graduations de taille Fahrenheit ; 0 est le zéro absolu.',
    '°C': 'Degré Celsius — échelle où l’eau gèle à 0° et bout à 100°.',
    'K': 'Kelvin — unité de base SI de température, comptée à partir du zéro absolu.',
  },
  UnitCategory.press: {
    'psi': 'Livre par pouce carré — mesure de pression impériale (un lbf sur une surface d’un pouce carré).',
    'inHg': 'Pouce de mercure — pression maintenant une colonne de mercure à un pouce de hauteur.',
    'Pa': 'Pascal — unité SI de pression ; un newton par mètre carré.',
    'kPa': 'Kilopascal — mille pascals.',
    'bar': 'Bar — 100000 pascals, proche de la pression atmosphérique moyenne au niveau de la mer.',
    'atm': 'Atmosphère standard — pression atmosphérique moyenne au niveau de la mer (101325 pascals).',
    'mmHg': 'Millimètre de mercure (torr) — pression d’une colonne de mercure d’un millimètre de hauteur.',
  },
  UnitCategory.force: {
    'lbf': 'Livre-force — la force de gravité exercée sur une livre (4,448 N).',
    'pdl': 'Poundal — unité de force impériale qui accélère une livre à 1 ft/s² (0,138 N).',
    'N': 'Newton — unité SI de force ; accélère un kilogramme à 1 m/s².',
    'kN': 'Kilonewton — mille newtons.',
    'kgf': 'Kilogramme-force — la force de gravité exercée sur un kilogramme (9,807 N).',
    'dyn': 'Dyne — unité de force CGS ; accélère un gramme à 1 cm/s² (10⁻⁵ N).',
  },
  UnitCategory.work: {
    'BTU': 'British Thermal Unit — chaleur réchauffant une livre d’eau de 1 °F (1055 J).',
    'ft·lbf': 'Pied-livre — travail pour déplacer une livre-force sur un pied (1,356 J).',
    'J': 'Joule — unité SI d’énergie ; un newton sur un mètre.',
    'kJ': 'Kilojoule — mille joules.',
    'Wh': 'Wattheure — énergie d’une puissance d’un watt pendant une heure (3600 J).',
    'kWh': 'Kilowattheure — mille wattheures, l’unité habituelle des factures d’électricité.',
    'cal': 'Calorie — chaleur réchauffant un gramme d’eau de 1 °C (4,184 J).',
    'kcal': 'Kilocalorie — mille calories ; la « calorie » de la nutrition.',
  },
  UnitCategory.power: {
    'hp': 'Cheval-vapeur (mécanique, impérial) — environ 745,7 watts.',
    'BTU/h': 'BTU par heure — mesure de puissance utilisée principalement en chauffage et climatisation (0,293 W).',
    'W': 'Watt — unité SI de puissance ; un joule par seconde.',
    'kW': 'Kilowatt — mille watts.',
    'PS': 'Cheval-vapeur (métrique) — 735,5 watts.',
  },
  UnitCategory.cook: {
    'tsp': 'Cuillère à café (US) — mesure de cuisine, un tiers de cuillère à soupe (4,93 ml).',
    'tbsp': 'Cuillère à soupe (US) — mesure de cuisine de trois cuillères à café (14,79 ml).',
    'fl oz': 'Once liquide (US) — mesure de volume pour les liquides (29,57 ml).',
    'cup': 'Tasse (US) — mesure de cuisine de huit onces liquides (236,6 ml).',
    'pint': 'Pinte (US) — deux tasses, soit 16 onces liquides (473,2 ml).',
    'mL': 'Millilitre — un millième de litre, soit un centimètre cube.',
    'L': 'Litre — mesure de volume métrique, un décimètre cube.',
  },
  UnitCategory.liquid: {
    'fl oz': 'Once liquide (US) — mesure de volume pour les liquides (29,57 ml).',
    'gill': 'Gill — ancienne mesure de liquide, un quart de pinte (118,3 ml).',
    'pint': 'Pinte (US) — 16 onces liquides, soit quatre gills (473,2 ml).',
    'quart': 'Quart — un quart de gallon, soit deux pintes (0,946 l).',
    'gallon': 'Gallon (US) — quatre quarts (3,785 l).',
    'mL': 'Millilitre — un millième de litre.',
    'L': 'Litre — mesure de volume métrique, un décimètre cube.',
  },
  UnitCategory.moment: {
    'lbf·ft': 'Livre-pied — le couple d’une livre-force sur un levier d’un pied (1,356 N·m).',
    'lbf·in': 'Livre-pouce — le couple d’une livre-force sur un levier d’un pouce (0,113 N·m).',
    'N·m': 'Newton-mètre — unité SI de couple ; un newton sur un levier d’un mètre.',
    'kN·m': 'Kilonewton-mètre — mille newton-mètres.',
    'kgf·m': 'Kilogramme-force mètre — le couple d’un kilogramme-force sur un levier d’un mètre (9,807 N·m).',
  },
};
